before:
  hooks:
    - go mod tidy
    - go mod download
builds:
- main: ./cmd/main.go
archives:
- replacements:
    darwin: Darwin
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github