coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
    patch: off
    changes: false
    
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes