---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - custom-autoscaling.sample.com
  resources:
  - customhorizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custom-autoscaling.sample.com
  resources:
  - customhorizontalpodautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - custom-autoscaling.sample.com
  resources:
  - customhorizontalpodautoscalers/status
  verbs:
  - get
  - patch
  - update
