apiVersion: custom-autoscaling.sample.com/v1alpha1
kind: CustomHorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: customhorizontalpodautoscaler
    app.kubernetes.io/instance: sample-custom-hpa
    app.kubernetes.io/part-of: custom-horizontal-pod-autoscaler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: custom-horizontal-pod-autoscaler
  name: sample-custom-hpa
spec:
  horizontalPodAutoscalerName: sample-hpa
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Pods
    pods:
      metric:
        name: memory_usage_bytes
      target:
        type: AverageValue
        averageValue: 8368128
  conditionalReplicasSpecs:
  - condition:
      type: workday
      id: 7-21
    minReplicas: 2
    maxReplicas: 4
  - condition:
      type: training
      id: 7-21
    minReplicas: 5
    maxReplicas: 10
