apiVersion: custom-autoscaling.sample.com/v1
kind: CustomHorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: customhorizontalpodautoscaler
    app.kubernetes.io/instance: customhorizontalpodautoscaler-sample
    app.kubernetes.io/part-of: custom-horizontal-pod-autoscaler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: custom-horizontal-pod-autoscaler
  name: customhorizontalpodautoscaler-sample
spec:
  horizontalPodAutoscalerName: custom-hpa
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-deployment
  minReplicas: 2
  maxReplicas: 4
  minReplicasTraining: 5
  maxReplicasTraining: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: memory_usage_bytes
      target:
        type: Value
        averageValue: 8368128
