name: Create release

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    # types: [closed]

jobs:
  create_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build docker image
      run: |
        make docker-build IMG=ghcr.io/$GITHUB_ACTOR/custom-horizontal-pod-autoscaler:latest \
        docker tag ghcr.io/$GITHUB_ACTOR/custom-horizontal-pod-autoscaler:latest ghcr.io/$GITHUB_ACTOR/custom-horizontal-pod-autoscaler:$(echo $GITHUB_SHA | head -c7)
    - name: push docker image
      run: |
        make docker-push IMG=ghcr.io/$GITHUB_ACTOR/custom-horizontal-pod-autoscaler:latest
        make docker-push IMG=ghcr.io/$GITHUB_ACTOR/custom-horizontal-pod-autoscaler:$(echo $GITHUB_SHA | head -c7)
