name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      release_level:
        type: choice
        description: 'select release level'
        default: minor
        options:
          - major
          - minor
          - patch
        required: true

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.get-latest-tag.outputs.tag != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ github.event.inputs.release_level }}

      - name: Make changes to pull request
        if: ${{ steps.bump-semver.outputs.new_version != null }}
        run: |
          date +%s > .version 
          echo ${{ steps.bump-semver.outputs.new_version }} >> .version

      - name: Create New Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'Create new release.'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          title: 'Create new release.'
          body: |
            Auto-generated by [create-pull-request][1]
  
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            release/${{ github.event.inputs.release_level }}
          draft: false
          branch: release
          delete-branch: true

      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto "1"
